<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DisableParallelization>true</DisableParallelization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EnumerablePrinter\EnumerablePrinter.csproj" />
    <ProjectReference Include="..\..\samples\EnumerablePrinter.Demo\EnumerablePrinter.Demo.csproj" />
  </ItemGroup>

</Project>
