name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: |
          dotnet restore src/EnumerablePrinter/EnumerablePrinter.csproj
          dotnet restore tests/EnumerablePrinter.Tests/EnumerablePrinter.Tests.csproj

      - name: Build
        run: |
          dotnet build src/EnumerablePrinter/EnumerablePrinter.csproj --configuration Release --no-restore
          dotnet build tests/EnumerablePrinter.Tests/EnumerablePrinter.Tests.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test tests/EnumerablePrinter.Tests/EnumerablePrinter.Tests.csproj --no-build --verbosity normal
